import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import Navbar from "./components/sections/navbar";
import ChatWidget from "./components/sections/chatwidget";

export const metadata: Metadata = {
  title: "Freelancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="">{children}</main>
        <ChatWidget />

  
      </body>
    </html>
  );
}
